
name = "OLED Featherwing (128x64)"
manufacturer = "Adafruit"
is_main_board = false
standard = "Feather"

related_crates = ["sh1107"]

bsp = "iron-coder-featherwing-oled-bsp"

[[pinout]]
pins = ["8", "9"]
interface = { iface_type = "I2C", direction = "Input" }